=== Ptg2001/SDL_ALL_CODES/XML_validation/carrental.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="carrentals">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="carrental" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="renter" type="xs:string"/>
              <xs:element name="rentalinfo">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="car" type="xs:string"/>
                    <xs:element name="rentaldate" type="xs:date"/>
                    <xs:element name="returndate" type="xs:date"/>
                    <xs:element name="pickuplocation" type="xs:string"/>
                    <xs:element name="returnlocation" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="additionalinfo" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="specialrequests" type="xs:string" minOccurs="0"/>
                    <xs:element name="insurance" type="xs:boolean" default="false"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="rentalid" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== Ptg2001/SDL_ALL_CODES/XML_validation/carrentals.xml
<?xml version="1.0" encoding="UTF-8"?>
<carrentals xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="carrental.xsd">

  <carrental rentalid="ABC123">
    <renter>Piyush</renter>

    <rentalinfo>
      <car>BMW</car>
      <rentaldate>2024-02-06</rentaldate>
      <returndate>2024-02-13</returndate>
      <pickuplocation>Zoop Cars</pickuplocation>
      <returnlocation>Zoop Cars</returnlocation>
    </rentalinfo>

    <additionalinfo>
      <specialrequests>GPS Navigation</specialrequests>
      <insurance>true</insurance>
    </additionalinfo>
  </carrental>

  <carrental rentalid="DEF456">
    <renter>Rajesh</renter>

    <rentalinfo>
      <car>Mercedes</car>
      <rentaldate>2024-02-08</rentaldate>
      <returndate>2024-02-15</returndate>
      <pickuplocation>Rapid Rent</pickuplocation>
      <returnlocation>Rapid Rent</returnlocation>
    </rentalinfo>

    <additionalinfo>
      <specialrequests>Child Seat</specialrequests>
      <insurance>true</insurance>
    </additionalinfo>
  </carrental>

</carrentals>
